- name: mongodb
  hosts: mongodb
  become: yes
  tasks:
  - name: copy mongodb repo 
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb
    ansible.builtin.package:
      name: mongodb-org
      state: present

  - name: start and run mongodb
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes

  - name: provide root access
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: restart mongod
    ansible.builtin.service:
      name: mongod
      state: restared
      
    
     

